In [14]:
a = {}
a['ano'] = {}
a['ano']['bno'] = 1
a[2] = {}
a[2][1] = 4

In [15]:
a

{'ano': {'bno': 1}, 2: {1: 4}}

In [12]:
a.get('cno', None).get('bno', None)

AttributeError: 'NoneType' object has no attribute 'get'

## Importing Libraries

In [1]:
import os
os.chdir('/home/shivam13juna/Documents/learn/allRank/')

import re
import pandas as pd
from sklearn.datasets import dump_svmlight_file

pd.options.display.max_columns = 500
pd.options.display.max_rows = 500



## Analyzing txt file

In [45]:
data_loc = 'allrank/pony_data/train.txt'

with open(data_loc, 'r') as handle:
    file = handle.readlines()

In [46]:
file[0]

'1 qid:1 0:3 1:56 2:462 3:1200 4:3\n'

In [47]:
cont = {}
for i in file:
    
    value = re.search('qid:(\d+)\s+.*', i).group(1)

    if value in cont:
        cont[value] += 1
    else:
        cont[value] = 1

Sorting by counts

In [48]:
sorted(cont.items(), key=lambda x: x[1], reverse=True)[:5]

[('14900', 36), ('14895', 36), ('14907', 36), ('14930', 36), ('14944', 36)]

Sorting by numerical key

In [39]:
sorted(cont.items(), key=lambda x: int(x[0]), reverse=True)[:5]

[('18387', 12), ('18386', 15), ('18385', 13), ('18384', 11), ('18383', 12)]

In [54]:
fin.sort_values('match_record_id', ascending=False).groupby('match_record_id')['h_no'].nunique()

match_record_id
1        16
2        16
3        15
4        16
5        16
         ..
18383    12
18384    11
18385    13
18386    15
18387    12
Name: h_no, Length: 15664, dtype: int64

In [41]:
for i in file:
    if '14900' in i:
        print(i)


13 qid:14900 0:8 1:53 2:480 3:1400 4:2

13 qid:14900 0:8 1:53 2:480 3:1400 4:2

17 qid:14900 0:7 1:54 2:506 3:1400 4:2

17 qid:14900 0:7 1:54 2:506 3:1400 4:2

16 qid:14900 0:6 1:52 2:432 3:1400 4:2

16 qid:14900 0:6 1:52 2:432 3:1400 4:2

15 qid:14900 0:6 1:55 2:508 3:1400 4:2

15 qid:14900 0:6 1:55 2:508 3:1400 4:2

3 qid:14900 0:5 1:56 2:484 3:1400 4:2

3 qid:14900 0:5 1:56 2:484 3:1400 4:2

10 qid:14900 0:5 1:54 2:472 3:1400 4:2

10 qid:14900 0:5 1:54 2:472 3:1400 4:2

12 qid:14900 0:5 1:52 2:454 3:1400 4:2

12 qid:14900 0:5 1:52 2:454 3:1400 4:2

9 qid:14900 0:5 1:52 2:440 3:1400 4:2

9 qid:14900 0:5 1:52 2:440 3:1400 4:2

14 qid:14900 0:5 1:52 2:450 3:1400 4:2

14 qid:14900 0:5 1:52 2:450 3:1400 4:2

8 qid:14900 0:5 1:53 2:482 3:1400 4:2

8 qid:14900 0:5 1:53 2:482 3:1400 4:2

11 qid:14900 0:5 1:54 2:430 3:1400 4:2

11 qid:14900 0:5 1:54 2:430 3:1400 4:2

5 qid:14900 0:4 1:53 2:438 3:1400 4:2

5 qid:14900 0:4 1:53 2:438 3:1400 4:2

4 qid:14900 0:4 1:55 2:488 3:1400 4:2

4 qid:149

## Analyzing csv

In [1]:
import os
os.chdir('/home/shivam13juna/Documents/learn/allRank/')

import re
import pandas as pd
from sklearn.datasets import dump_svmlight_file

pd.options.display.max_columns = 500
pd.options.display.max_rows = 500



# fin = pd.read_csv(os.path.expanduser('~/Documents/upwork/baran_pony/processed_data.csv'))
train_data = pd.read_csv('~/Documents/upwork/baran_pony/tmp/train_data.csv')
test_data = pd.read_csv('~/Documents/upwork/baran_pony/tmp/test_data.csv')

In [2]:
train_data['checkr'] = train_data['match_record_id']
test_data['checkr'] = test_data['match_record_id']


train_data.drop_duplicates(['match_record_id', 'horse_name', 'h_no'], inplace=True)
test_data.drop_duplicates(['match_record_id', 'horse_name', 'h_no'], inplace=True)



In [3]:
train_data.sort_values('match_record_id', inplace=True)
test_data.sort_values('match_record_id', inplace=True)

In [4]:
print("Shape of train data: ", train_data.shape)
print("Shape of test data: ", test_data.shape, end='\n\n')
print("No of unique matches in train data: ", train_data['match_record_id'].nunique())
print("No of unique matches in test data: ", test_data['match_record_id'].nunique())


Shape of train data:  (143126, 36)
Shape of test data:  (44317, 32)

No of unique matches in train data:  10356
No of unique matches in test data:  3706


In [5]:
train_data['rank'] = train_data['place'].apply(lambda x: 18 - x)
test_data['rank'] = test_data['place'].apply(lambda x: 18 - x)

In [8]:
feature_list = ['h_age', 'jockey_wt', 'horse_wt', 'race_length', 'track', 'odds_tan', 'odds_fuku', 'checkr']

train_x = train_data[feature_list]
train_y = train_data['rank']

test_x = test_data[feature_list]
test_y = test_data['rank']

dump_svmlight_file(X=train_x, y=train_y, f='allrank/pony_data/train.txt', query_id = train_data['match_record_id'], zero_based=True)
print("Dumped train data to file")
dump_svmlight_file(X=test_x, y=test_y, f='allrank/pony_data/vali.txt', query_id = test_data['match_record_id'], zero_based=True)
print("Dumped test data to file")

import shutil
shutil.copy('allrank/pony_data/vali.txt', 'allrank/pony_data/test.txt')
print("Copied vali data to test")

Dumped train data to file
Dumped test data to file
Copied vali data to test


In [9]:
train_x[feature_list].head()

h_age  jockey_wt  horse_wt  race_length  track  odds_tan  odds_fuku  \
0       3       56.0       462         1200      3       2.0        1.1   
58      3       56.0       486         1200      3      19.2        3.5   
65      3       56.0       484         1200      3       7.5        1.9   
73      3       51.0       482         1200      3      26.8        4.7   
89      3       54.0       428         1200      3      10.8        2.0   

    checkr  
0        1  
58       1  
65       1  
73       1  
89       1

In [6]:
test_data.loc[(test_data['odds_tan'] == 79.8) & (test_data['odds_fuku'] == 11), 'match_record_id']

2    11579
Name: match_record_id, dtype: int64

In [7]:
test_data.loc[(test_data['odds_tan'] == 32.4) & (test_data['odds_fuku'] == 11), 'match_record_id']

Series([], Name: match_record_id, dtype: int64)

In [8]:
test_data.loc[test_data['match_record_id'] == 11579, ['h_no', 'h_age', 'odds_tan', 'odds_fuku', 'place']].sort_values('place')

h_no  h_age  odds_tan  odds_fuku  place
35449     7      3      12.9        2.8    1.0
30587    12      3       5.6        1.9    2.0
20910    11      3       9.5        2.2    3.0
32944    15      3      54.5       10.1    5.0
35433     6      3       4.1        1.5    6.0
35462     9      3      63.4        9.9    7.0
29607    10      3       4.1        1.5    9.0
30610     5      3      78.0       10.4   10.0
38171    16      3      42.7        7.7   11.0
35485    14      3     218.2       23.6   12.0
2         4      3      79.8       11.0   13.0
8020      8      3     334.5       43.3   14.0
35475     2      3     286.1       34.6   15.0
29106     1      3      84.8       12.3   16.0

In [9]:
test_data['match_record_id'].nunique()

3706

In [13]:
from sklearn.datasets import load_svmlight_file

x, y, query_ids = load_svmlight_file('allrank/pony_data/test.txt', query_id=True)

In [15]:
print("Shape of x: ", x.shape)
print("Shape of y: ", y.shape)
print("Shape of query_ids: ", query_ids.shape)


Shape of x:  (44317, 8)
Shape of y:  (44317,)
Shape of query_ids:  (44317,)


In [18]:
query_ids[:100]

array([10370, 10370, 10370, 10370, 10370, 10370, 10370, 10370, 10370,
       10370, 10370, 10370, 10370, 10370, 10370, 10370, 10371, 10371,
       10371, 10371, 10371, 10371, 10371, 10371, 10371, 10371, 10371,
       10371, 10371, 10371, 10371, 10371, 10373, 10373, 10373, 10373,
       10373, 10373, 10373, 10373, 10373, 10373, 10373, 10373, 10373,
       10373, 10373, 10374, 10374, 10374, 10374, 10374, 10374, 10374,
       10374, 10374, 10374, 10374, 10374, 10374, 10374, 10374, 10374,
       10375, 10375, 10375, 10375, 10375, 10375, 10375, 10375, 10375,
       10375, 10375, 10376, 10376, 10376, 10376, 10376, 10376, 10376,
       10376, 10376, 10376, 10376, 10376, 10376, 10376, 10376, 10376,
       10377, 10377, 10377, 10377, 10377, 10377, 10377, 10377, 10377,
       10377])

# Inference

In [36]:
import os
os.chdir('/home/shivam13juna/Documents/learn/allRank/')


import torch
import numpy as np
import pandas as pd
import allrank.models.losses as losses


from allrank.config import Config
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from allrank.models.model import LTRModel
from allrank.models.model import make_model
from allrank.models.metrics import ndcg, dcg
from typing import Tuple, Dict, List, Generator
from torch.utils.data.dataloader import DataLoader
from allrank.data.inf_dataset_loading import *
from allrank.models.model_utils import *
from allrank.inference.inference_utils import __rank_slates



from allrank.utils.python_utils import all_equal
from attr import asdict

In [37]:
topn = 20
test_path = f'pony/results/pony'
# dev = get_torch_device()
dev = torch.device("cpu")

#creating datset and dataloader instances
test_ds = load_libsvm_dataset_role('test', 'allrank/pony_data/', topn )
_, test_dl = create_data_loaders(test_ds, test_ds, num_workers=1, batch_size=test_ds.shape[0])

n_features = test_ds.shape[-1]
assert all_equal([n_features]), f"Last dimensions of datasets must match but got {n_features}"

#loading trained model
config = Config.from_json(f'{test_path}/used_config.json')
model = make_model(n_features=n_features, **asdict(config.model, recurse=False))
model.load_state_dict(load_state_dict_from_file(f'{test_path}/model.pkl', dev))

<All keys matched successfully>

In [38]:
x_, y_ = __rank_slates(test_dl, model)

with open(f'{test_path}/test_pred.csv', 'w') as f:
        f.write(f'qid,eid,pred_score,true_sorted_by_pred\n')
        for i, (qid, count) in enumerate(test_dl.dataset.query_ids.items()):
            for j in range(count):
                f.write(f'{qid},{int(x_[i, j, -1])},{topn - j},{int(y_[i, j])}\n')
    
#again do the prediction for metrics calculation. I couldn't find a better way to do it reusing *y_ * in the above
# results = compute_metrics(config.metrics, model, test_dl, dev)

In [39]:
x_[0].shape

torch.Size([18, 7])

In [40]:
y_[0].shape

torch.Size([18])

In [6]:
np.set_printoptions(formatter={'all':lambda x: str(x)})

In [41]:
print("X: ", x_[0].numpy())
print("Y: ", y_[0])



X:  [[3.0 56.0 466.0 1200.0 3.0 1.8 1.1]
 [3.0 54.0 452.0 1200.0 3.0 5.3 1.3]
 [3.0 51.0 452.0 1200.0 3.0 8.9 1.6]
 [3.0 56.0 516.0 1200.0 3.0 9.0 2.0]
 [3.0 55.0 488.0 1200.0 3.0 13.6 2.7]
 [3.0 56.0 460.0 1200.0 3.0 15.7 2.1]
 [3.0 56.0 484.0 1200.0 3.0 17.9 3.8]
 [3.0 56.0 446.0 1200.0 3.0 29.5 5.2]
 [3.0 56.0 472.0 1200.0 3.0 41.6 5.7]
 [3.0 56.0 488.0 1200.0 3.0 43.0 6.7]
 [3.0 54.0 414.0 1200.0 3.0 103.0 13.5]
 [3.0 55.0 460.0 1200.0 3.0 108.4 16.2]
 [3.0 53.0 416.0 1200.0 3.0 116.9 14.2]
 [3.0 52.0 438.0 1200.0 3.0 181.1 34.1]
 [3.0 54.0 412.0 1200.0 3.0 337.3 45.2]
 [3.0 53.0 434.0 1200.0 3.0 440.6 69.3]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0]]
Y:  tensor([17., 12., 16., 13., 15., 14., 10.,  6.,  8.,  3.,  7., 11.,  4.,  9.,
         2.,  5., -1., -1.])


In [54]:
count = 0
net = 0

for i in y_:
    a = np.array(i)
    if a[0] == 17 or a[1] == 17 or a[2] == 17:
        count += 1
        net += 1
    else:
        net += 1
print("Accuracy: ", count/net, count, net)

Accuracy:  0.5833783054506206 2162 3706


In [56]:
import joblib
import pandas as pd
import seaborn as sns
import xgboost as xgb
import matplotlib.pyplot as plt


from lib import sorter

from xgboost import DMatrix
from functools import reduce
from numerize import numerize
from datetime import datetime, date
from sklearn.model_selection import GroupShuffleSplit



gbm_model = joblib.load('/home/shivam13juna/Documents/upwork/baran_pony/tmp/gbm_model.pkl')
def predict(model, data, feature_list):
    predictions = np.argsort(model.predict(DMatrix(data[feature_list].values)))
    # print('*' * 100)
    # print("we predictions:", predictions)
    # print("they predictions: ", data.iloc[predictions]['place'].values)
    # print("act_place: ", data['place'].values)
    # print('*' * 100)
    return data.iloc[predictions]['place'].values



def find_accuracy(output):
    try:
        count1 = 0
        count2 = 0
        count3 = 0
        out = 0
        for i in output:
            if len(i) < 3:
                continue
            try:
#                 if i[0] == 1 or i[1] == 1 or i[0] == 2 or i[1] == 2:
                if i[0] == 1 or i[1] == 1 or i[2] == 1:
                    count1+=1
                if i[0] == 1 or i[1] == 1 or i[2] == 1 or i[0] == 2 or i[1] == 2 or i[2] == 2:
                    count2+=1
                if i[0] == 1 or i[1] == 1 or i[2] == 1 or i[0] == 2 or i[1] == 2 or i[2] == 2 or i[0] == 3 or i[1] == 3 or i[2] == 3:
                    count3+=1
                out += 1
            except Exception as e:
                print(i)


        return count1/out, count2/out, count3/out, count1, out
    except:
        print("couldn't process, check data")
        
        
def find_wide(output):
    try:
        count = 0

        out = 0
        for i in output:
            if len(i) < 3:
                continue
            try:
                if (i[0] == 1 and i[1] == 2) or (i[0] == 2 and i[1] == 1) or (i[0] == 2 and i[1] == 3) or (i[0] == 3 and i[1] == 2) or (i[0] == 1 and i[1] == 3) or (i[0] == 3 and i[1] == 1):  
                    count += 1

                out += 1
            except:
                print(i)


        return count/out
    except:
        print("couldn't process, check data")

    
output = test_data.groupby('unq_id').apply(lambda x: predict(gbm_model, x, feature_list)).reset_index().rename(columns={0:'prediction'})
curr_acc = find_accuracy(output['prediction'].values)
# wide_acc = find_wide(output['prediction'].values)
print("Accuracy that one among the predicted top 3 is in rank 1: ", curr_acc[0])
print("Accuracy that one among the predicted top 3 is in rank 1 or 2: ", curr_acc[1])
print("Accuracy that one among the predicted top 3 is in rank 1 or 2 or 3: ", curr_acc[2])
print("count and net are: ", curr_acc[3], curr_acc[4])
# print("Wide Acc: ", wide_acc)

Accuracy that one among the predicted top 3 is in rank 1:  0.5794316644113667
Accuracy that one among the predicted top 3 is in rank 1 or 2:  0.7959404600811908
Accuracy that one among the predicted top 3 is in rank 1 or 2 or 3:  0.8976995940460081
count and net are:  2141 3695


In [8]:
# test_ds = load_libsvm_dataset_role('test', 'allrank/pony_data/', topn )
# _, test_dl = create_data_loaders(test_ds, test_ds, num_workers=1, batch_size=test_ds.shape[0])

for x, y, z in test_dl:
    break

In [9]:
print("x shape: ", x.shape)
print("y shape: ", y.shape)
print("z shape: ", z.shape)


x shape:  torch.Size([3706, 18, 8])
y shape:  torch.Size([3706, 18])
z shape:  torch.Size([3706, 18])


In [ ]:
reranked_X = []
reranked_y = []
model.eval()
# device = get_torch_device()
device = torch.device("cpu")
with torch.no_grad():
    for xb, yb, _ in test_dl:
        X = xb.type(torch.float32).to(device=device)
        y_true = yb.to(device=device)

        input_indices = torch.ones_like(y_true).type(torch.long)
        mask = (y_true == losses.PADDED_Y_VALUE)
        scores = model.score(X, mask, input_indices)

        scores[mask] = float('-inf')

        _, indices = scores.sort(descending=True, dim=-1)
        indices_X = torch.unsqueeze(indices, -1).repeat_interleave(X.shape[-1], -1)
        reranked_X.append(torch.gather(X, dim=1, index=indices_X).cpu())
        reranked_y.append(torch.gather(y_true, dim=1, index=indices).cpu())

combined_X = torch.cat(reranked_X)
combined_y = torch.cat(reranked_y)

In [17]:
value = model.score(x, (y == losses.PADDED_Y_VALUE), torch.ones_like(y).type(torch.long))

In [18]:
value.sort(descending=True, dim=-1)

torch.return_types.sort(
values=tensor([[0.8256, 0.7734, 0.6858,  ..., 0.5553, 0.0019, 0.0019],
        [0.7352, 0.7024, 0.6435,  ..., 0.5243, 0.0022, 0.0022],
        [0.8241, 0.5898, 0.5891,  ..., 0.0022, 0.0022, 0.0022],
        ...,
        [0.6273, 0.6271, 0.6269,  ..., 0.0018, 0.0018, 0.0018],
        [0.6219, 0.6172, 0.6125,  ..., 0.5971, 0.0018, 0.0018],
        [0.6405, 0.6356, 0.6311,  ..., 0.0017, 0.0017, 0.0017]],
       grad_fn=<SortBackward0>),
indices=tensor([[14,  1,  7,  ...,  0, 16, 17],
        [13,  2, 15,  ...,  6, 16, 17],
        [ 5, 13,  1,  ..., 15, 16, 17],
        ...,
        [ 2,  3,  5,  ...,  9,  8,  7],
        [ 5, 10,  4,  ...,  1, 16, 17],
        [ 3,  5,  2,  ..., 15, 16, 17]]))

In [16]:
y[0]

tensor([ 1., 16., 15., 14., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,
        13.,  2., -1., -1.])

In [13]:
x[0].numpy()

array([[3.0, 56.0, 466.0, 1200.0, 3.0, 1.8, 1.1, 10370.0],
       [3.0, 54.0, 412.0, 1200.0, 3.0, 337.3, 45.2, 10370.0],
       [3.0, 56.0, 488.0, 1200.0, 3.0, 43.0, 6.7, 10370.0],
       [3.0, 53.0, 416.0, 1200.0, 3.0, 116.9, 14.2, 10370.0],
       [3.0, 56.0, 446.0, 1200.0, 3.0, 29.5, 5.2, 10370.0],
       [3.0, 54.0, 414.0, 1200.0, 3.0, 103.0, 13.5, 10370.0],
       [3.0, 56.0, 472.0, 1200.0, 3.0, 41.6, 5.7, 10370.0],
       [3.0, 52.0, 438.0, 1200.0, 3.0, 181.1, 34.1, 10370.0],
       [3.0, 56.0, 484.0, 1200.0, 3.0, 17.9, 3.8, 10370.0],
       [3.0, 55.0, 460.0, 1200.0, 3.0, 108.4, 16.2, 10370.0],
       [3.0, 54.0, 452.0, 1200.0, 3.0, 5.3, 1.3, 10370.0],
       [3.0, 56.0, 516.0, 1200.0, 3.0, 9.0, 2.0, 10370.0],
       [3.0, 56.0, 460.0, 1200.0, 3.0, 15.7, 2.1, 10370.0],
       [3.0, 55.0, 488.0, 1200.0, 3.0, 13.6, 2.7, 10370.0],
       [3.0, 53.0, 434.0, 1200.0, 3.0, 440.6, 69.3, 10370.0],
       [3.0, 51.0, 452.0, 1200.0, 3.0, 8.9, 1.6, 10370.0],
       [0.0, 0.0, 0.0, 0.0, 0.0,

In [36]:
test_data.loc[(test_data['odds_tan'] == 79.8) & (test_data['odds_fuku'] == 11), 'match_record_id']


2    11579
Name: match_record_id, dtype: int64

In [49]:

test_data.loc[test_data['match_record_id'] == 10383, ['h_no', 'h_age', 'odds_tan', 'odds_fuku', 'place']].sort_values('place')

h_no  h_age  odds_tan  odds_fuku  place
1346     7      3       2.8        1.4    1.0
1360    16      3       5.0        1.6    2.0
1373     8      3       4.5        1.4    3.0
1386     6      3      14.9        2.9    4.0
1392     2      3     331.3       48.6    5.0
1405    10      3      10.4        2.4    6.0
1410     1      3      69.6       11.2    7.0
1418     4      3      51.9        7.4    8.0
1421    14      3     154.3       18.3    9.0
1424    15      3     157.2       19.1   10.0
1427    11      3       6.2        1.6   11.0
1432     3      3      42.8        7.0   12.0
1433    13      3      37.0        5.9   13.0
1436    12      3      48.3       10.3   14.0
1440     9      3      24.1        5.4   15.0
1448     5      3     308.3       48.6   16.0

In [12]:
def conv_libsvm_to_pandas(svmformat_file):
    # Read to list
    with open(svmformat_file, mode="r") as fp:
        svmformat_list = fp.readlines()

    # For each line we save the key:values to a dict
    pandas_list = []
    for line in svmformat_list:
        line_dict = dict()

        line_split = line.split(' ')
        line_dict["label"] = line_split[0]

        for col in line_split[1:]:
            col = col.rstrip()  # Remove '\n'
            col_split = col.split(':')
            key, value = col_split[0], col_split[1]
            line_dict[key] = value

        pandas_list.append(line_dict)
    return pd.DataFrame(pandas_list)
ano = conv_libsvm_to_pandas('allrank/pony_data/test.txt')

In [14]:
ano.head()

label    qid   0   1    2     3  4
0     8  18361   8  57  508  1700  3
1     6  18098   7  57  506  1200  2
2     9  18361   8  57  470  1700  3
3     9  18247  11  62  446  2750  2
4    11  17989  10  53  490  1400  2

In [15]:
ano['qid'].nunique()

408

In [7]:
for i, (qid, count) in enumerate(test_dl.dataset.query_ids.items()):
    print("i: ", i, "qid: ", qid, "count: ", count)

i:  0 qid:  18361 count:  13
i:  1 qid:  18098 count:  16
i:  2 qid:  18247 count:  13
i:  3 qid:  17989 count:  13
i:  4 qid:  18179 count:  12
i:  5 qid:  18122 count:  16
i:  6 qid:  18061 count:  16
i:  7 qid:  18277 count:  10
i:  8 qid:  18206 count:  14
i:  9 qid:  18327 count:  16
i:  10 qid:  18386 count:  15
i:  11 qid:  18170 count:  16
i:  12 qid:  18278 count:  16
i:  13 qid:  18073 count:  15
i:  14 qid:  18012 count:  7
i:  15 qid:  18084 count:  16
i:  16 qid:  18301 count:  12
i:  17 qid:  18229 count:  16
i:  18 qid:  18231 count:  16
i:  19 qid:  18086 count:  15
i:  20 qid:  18049 count:  16
i:  21 qid:  18112 count:  11
i:  22 qid:  18180 count:  15
i:  23 qid:  18013 count:  16
i:  24 qid:  18314 count:  12
i:  25 qid:  18192 count:  16
i:  26 qid:  18350 count:  14
i:  27 qid:  18216 count:  9
i:  28 qid:  18181 count:  16
i:  29 qid:  18244 count:  11
i:  30 qid:  18076 count:  12
i:  31 qid:  18292 count:  8
i:  32 qid:  18230 count:  17
i:  33 qid:  18037 coun

In [4]:
pred = pd.read_csv('pony/results/pony/test_pred.csv')

In [5]:
pred.head()

qid  eid  pred_score  true_sorted_by_pred
0  18361    2          20                   13
1  18361    2          19                   11
2  18361    3          18                    9
3  18361    2          17                   16
4  18361    2          16                    2

In [9]:
pred.groupby('qid')['eid'].nunique()

qid
17980    2
17981    2
17982    2
17983    2
17984    2
        ..
18383    2
18384    2
18385    2
18386    3
18387    3
Name: eid, Length: 408, dtype: int64

In [13]:
indices

[array([0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0.])]